l_polish:
  EDITOR_SETTINGS: "Ustawienia edytora"
  PERFORMANCE: "Wydajność"
  SPACE: "spacja"
  SPACES: "spacje"
  TAB: "tabulacja"
  TABS: "tabulacje"
  EXTERNAL_EDITOR: "Edytor zewnętrzny"
  EXTERNAL_EDITOR_DESC: "Edytor zewnętrzny, który będzie używany po kliknięciu przycisku edycji."
  SELECT_PROGRAM: "Wybierz program edytora"
  INDENTATION: "Wcięcie"
  INDENTATION_DESC: "Typ wcięcia, który będzie używany przy okazji korzystania z zewnętrznego edytora oraz w dymkach informacyjnych."
  PAGE_SIZE: "Rozmiar strony"
  PAGE_SIZE_DESC: "Liczba węzłów pokazywanych na stronę.\nIm więcej wyświetlanych węzłów, tym więcej czasu zajmuje ładowanie nowych."
  MAX_TOOLTIP_LINES: "Limit wierszy w dymkach"
  MAX_TOOLTIP_LINES_DESC: "Maksymalna liczba linijek wyświetlanych w dymkach informacyjnych."
  ENABLE_NODE_TAGS: "Etykiety"
  ENABLE_NODE_TAGS_DESC: "Etykiety obniżają wydajność - każdy z węzłów musi być przeanalizowany, aby określić, jaka etykieta ma zostać wyświetlona."
  ENABLE_NODE_JUMPS: "Skoki między węzłami"
  ENABLE_NODE_JUMPS_DESC: "Skoki międzywęzłowe obniżają wydajność - każdy z węzłów musi być przeanalizowany, aby określić, gdzie należy wykonać skok."
  WARN_ON_TYPE_CHANGE: "Ostrzeżenie przy zmianie typu danych"
  WARN_ON_TYPE_CHANGE_DESC: "Wyświetla ostrzeżenie w razie zmieniania typu danych danego wpisu, co jest przeważnie niepożądane."
  EXTERNAL_EDITOR_WAIT_INTERVAL: "Czas opóźnienia odświeżania pliku z edytora zewnętrznego (ms)"
  EXTERNAL_EDITOR_WAIT_INTERVAL_DESC: "Zapisując plik przy użyciu edytora zewnętrznego, edytor Pdx-Unlimiter czeka określony czas, zanim dokona jego odczytu. Ma to za zadanie zapobiec błędom wynikającym ze zbyt wczesnego odczytu w przypadku, gdy twój dysk jest zbyt wolny."