l_polish:
 SETTINGS: "Ustawienia"
 INTERFACE: "Interfejs"
 GENERAL: "Główne"
 IMPORTS: "Importy"
 IRONY: "Irony mod manager"
 USE_GAME_LANGUAGE: "Używaj języka gry"
 MAX_TOOLTIP_SIZE: "Szerokość dymka informacyjnego"
 MAX_TOOLTIP_SIZE_DESC: "Maksymalna szerokość dymka informacyjnego w pikselach."
 USE_GAME_LANGUAGE_DESC: "Zawsze używaj języka, w którym jest obecnie wybrana gra.\nGdy ta opcja jest włączona, ustawianie języka poniżej nie jest używane. Miej na uwadze, że tłumaczenia są niepełne!"
 LANGUAGE: "Język"
 LANGUAGE_DESC: "Niestandardowy język interfejsu.\nOpcja brana pod uwagę tylko, jeśli "Używaj języka gry" jest odznaczone."
 SELECT_DIR: "Wybierz ścieżkę $DIR$"
 CHOICE_VALUE_ERROR: "Wartość $VAL$ jest nieprawidłowa. Przywrócona została wartość domyślna."
 GAME_DIRS: "Ścieżki instalacyjne gier"
 GAME_DIR_ERROR: "Wystąpił błąd podczas ładowania instalacji gry $GAME$"
 GAME_DIR_ERROR_MSG: "Wsparcie dla $GAME$ zostało wyłączone. Jeśli jesteś pewny, że instalacja jest prawidłowa, proszę sprawdź, czy ścieżka instalacyjna jest określona prawidłowo."
 GAME_DIR: "Ścieżka $GAME$"
 GAME_DIR_DESC: "Ścieżka instalacyjna $GAME$.\n\nPowinna być to ścieżka zawierająca plik wykonawczy, NIE ścieżka z Dokumentów, zawierająca twoje zapisy i modyfikacje."
 STORAGE_DIR: "Ścieżka przechowywania zapisów"
 STORAGE_DIR_DESC: "Lokalizacja, w której Pdx-Unlimiter przechowuje wszystkie zaimportowane zapisy.\nJest ona całkowicie niepodlegająca lokalizacjom, w których gry zapisują twoje kampanie automatycznie."
 STORAGE_DIR_DIALOG_TITLE: "Potwierdź przeniesienie lokalizacji z zapisami"
 STORAGE_DIR_DIALOG_TEXT: "Próbujesz przenieść swój folder wraz z zapisami z $FROM$\ndo $TO$.\nTo może chwilę potrwać."
 STORAGE_DIR_SAVEGAME_WARNING_TITLE: "Nieprawidłowa ścieżka do przechowywania zapisów"
 STORAGE_DIR_SAVEGAME_WARNING_TEXT: "Określona przez ciebie ścieżka jako lokalizacja przechowywania programu Pdx-Unlimiter wygląda na ścieżkę używaną przez grę.\nLokalizacja zapisów Pdx-Unlimiter jest całkowicie niepodlegająca lokalizacjom, w których gry zapisują twoje kampanie automatycznie."
 STORAGE_DIR_RESET_TITLE: "Ścieżka przechowywania zapisów nie istnieje"
 STORAGE_DIR_RESET_TEXT: "Ścieżka przechowywania zapisów $PATH$ nie istnieje lub nie jest prawidłowa. Czy chcesz przywrócić ścieżkę domyślną?"
 STORAGE_DIR_INVALID_TITLE: "Ścieżka przechowywania zapisów nie istnieje"
 STORAGE_DIR_INVALID_TEXT: "Ścieżka przechowywania zapisów $PATH$ nie istnieje lub nie jest prawidłowa."
 EU4SE: "Eu4SaveEditor"
 ENABLE_EU4SE: "Włącz Eu4SaveEditor"
 ENABLE_EU4SE_DESC: "Określa, czy włączyć Eu4SaveEditor.\n\nJeśli włączysz tę opcję, Eu4SaveEditor zostanie pobrany oraz zainstalowany przy następnym uruchomieniu Pdx-Unlimiter"
 MISC: "Inne"
 FONT_SIZE: "Rozmiar czcionki"
 FONT_SIZE_DESC: "Rozmiar czcionki używanej przez program.\n\nJeśli posiadasz ekran o wysokiej rozdzielczości, powiększenie czcionki może polepszyć czytelność tekstu."
 ENABLE_AUTOUPDATE: "Włącz aktualizacje automatyczne"
 ENABLE_AUTOUPDATE_DESC: "Określa, czy Pdx-Unlimiter i jego składniki mają zostać automatycznie aktualizowane przy starcie programu."
 CONFIRM_DELETION: "Potwierdzaj usunięcie"
 CONFIRM_DELETION_DESC: "Określa, czy program ma pytać zabezpieczająco przed usunięciem kampanii bądź zapisu."
 START_STEAM: "Uruchom poprzez Steam"
 START_STEAM_DESC: "Określa, czy uruchamiać platformę Steam przy uruchamianiu gry poprzez Pdx-Unlimiter,\n\nWyłączenie tej opcji może spowodować, że Steam nie będzie wykrywał osiągnięć zdobytych podczas rozgrywki."
 DELETE_ON_IMPORT: "Usuń pierwotny zapis po zaimportowaniu"
 DELETE_ON_IMPORT_DESC: "Określa, czy program usunie zapisy po prawidłowym zaimportowaniu ich do lokalizacji przechowania Pdx-Unlimiter."
 SKANDERBEG: "Skanderbeg.pm"
 SKANDERBEG_API_KEY: "Klucz API"
 SKANDERBEG_API_KEY_DESC: "Twój klucz API Skanderbeg.pm.\n\nZnajdziesz go kierując się na stronę "API" na Skanderbeg.pm."
 CONVERTERS: "Konwertery Paradox"
 CK3_TO_EU4_DIR: "Konwerter CK3 do EU4"
 CK3_TO_EU4_DIR_DESC: "Ścieżka do konwertera CK3ToEu4."
 IRONY_DIR: "Ścieżka instalacyjna"
 IRONY_DIR_DESC: "Ścieżka instalacyjna Irony."
 LAUNCH_IRONY: "Uruchom Irony"
 LAUNCH_IRONY_DESC: "Uruchamia manager modyfikacji Irony zamiast klienta Paradox."
 TIMED_IMPORTS: "Uruchom planowane importy"
 TIMED_IMPORTS_DESC: "Włącza automatyczne importowanie ostatniego zapisu po określonym czasie rozgrywki.."
 TIMED_IMPORTS_INTERVAL: "Minuty pomiędzy importami"
 TIMED_IMPORTS_INTERVAL_DESC: "Interwał pomiędzy automatycznymi importami w minutach."
 THIRD_PARTY_ERROR: "Wsparcie dla $APP$ zostało wyłączone.\nJeśli jesteś pewny, że instalacja jest prawidłowa, proszę sprawdź, czy ścieżka instalacyjna jest określona prawidłowo."
 PLAY_SOUND_ON_BACKGROUND_IMPORT: "Zagraj dźwięk przy importowaniu w tle"
 PLAY_SOUND_ON_BACKGROUND_IMPORT_DESC: "Jeśli program działa w tle, zagra dźwięk brzęczyka przy zaimportowaniu zapisu podczas uruchomionej gry."
 XBOX_UNAVAILABLE: "Ta gra nie jest dystrybuowana w Windows Store."
 XBOX_DIST_BUTTON: "Wybierz dystrybucję Windows Store.\nTo działa jedynie, gdy posiadasz zainstalowaną wersję gry z Windows Store."
 CLEAR_DIST_BUTTON: "Wyczyść obecnie wybraną dystrybucję gry."
 BROWSE_DIST_BUTTON: "Określ ścieżkę instalacyjną manualnie."
 IMPORT_ON_NORMAL_GAME_EXIT: "Zaimportuj przy wyjściu z gry"
 IMPORT_ON_NORMAL_GAME_EXIT_DESC: "Automatycznie importuje ostatni zapis podczas normalnego zamknięcia gry, tj. nie savescummując."